import {
  GraphQLObjectType,
  GraphQLNonNull,
  GraphQLBoolean,
  GraphQLString,
  GraphQLInputObjectType,
} from 'graphql';

export const Cookies = new GraphQLObjectType({
  name: 'Cookies',
  description: 'Cookies generated by pooky',
  fields: () => ({
    pooky: {
      type: GraphQLNonNull(GraphQLString),
      description: '55bd0c5d-2e36-4f4f-aeb9-eaa8fe00aecf',
    },
    pooky_owl: {
      type: GraphQLNonNull(GraphQLString),
      description: '6800974eb7b26d7408c0c617a53388d744349b640cdc34ba61f2f4829fbf7ced',
    },
    pooky_data: {
      type: GraphQLNonNull(GraphQLString),
      description: 'b4ad1771e7278cd938c0789dccf528c6935c70b50d1300ac03abbb50e857bfd0',
    },
    pooky_electric: {
      type: GraphQLNonNull(GraphQLString),
      description: 'ca5d35456efc96de36af9274269bbcbcd2c158c846c4051baaa2de5efa574e2e',
    },
    pooky_order_allow: {
      type: GraphQLNonNull(GraphQLString),
      description:
        'eyJ0b2hydV9vayI6IHRydWUsImVuYWJszwiQOiB0cnVlLCJhbGxfcmVsZWFzZXMiOnRydWUsInNwbGF5X2VudiI6InByb2QiLCAibW91c2Vfc2NvcmUiOjEwMCwiYnlwYXNzIjp0cnVlfQ',
    },
    pooky_performance: {
      type: GraphQLNonNull(GraphQLString),
      description:
        '90ff67084a669a673d32424c716f6f6b98a59dd83d5116e8187df230550341b892fff72ab92932237c175603d6f4fdc4',
    },
    pooky_recaptcha: {
      type: GraphQLNonNull(GraphQLString),
      description:
        'e97aea62ce991cbb72af50a9d79110d6fe4b7eac7e44abbb87bebcb5095b88c1edd028289cebf2c1fb1e69d684b8595f',
    },
    pooky_recaptcha_coherence: {
      type: GraphQLNonNull(GraphQLString),
      description:
        '0a48537c18a172c964265b8e0487a8e1d1f09151920859249c2f1d2a2c05fa1b57fd5c2a5766ad2545c43847ce4cc3d5',
    },
    pooky_settings: {
      type: GraphQLNonNull(GraphQLString),
      description:
        '6bca6fffcbd6aa398905fb9dc2a3ca1f8c803de2eee4f45fb41a4ffc70061fa1f5d3575bf720aabc2be8efb74d850bec',
    },
    pooky_telemetry: {
      type: GraphQLNonNull(GraphQLString),
      description:
        '67db023465119f3486c7aae6378e1b6eed727986fa248edbb36322217cc997baa78579a0239e472d3e1f343e2f79b318',
    },
    pooky_use_cookie: {
      type: GraphQLNonNull(GraphQLBoolean),
      description: 'true',
    },
    updated_pooky_coherence: {
      type: GraphQLNonNull(GraphQLString),
      description: 'bafd60d036cf80654d46b78341625b11ba67fe510fbbba40d71c00ed6a8f59cb',
    },
  }),
});

export const CookiesInputType = new GraphQLInputObjectType({
  name: 'CookiesInput',
  description: 'Input data to create/edit a Cookies Object',
  fields: () => ({
    pooky: {
      type: GraphQLString,
      description: '55bd0c5d-2e36-4f4f-aeb9-eaa8fe00aecf (uuid v4)',
    },
    pooky_owl: {
      type: GraphQLString,
      description: '6800974eb7b26d7408c0c617a53388d744349b640cdc34ba61f2f4829fbf7ced',
    },
    pooky_data: {
      type: GraphQLString,
      description: 'b4ad1771e7278cd938c0789dccf528c6935c70b50d1300ac03abbb50e857bfd0',
    },
    pooky_electric: {
      type: GraphQLString,
      description: 'ca5d35456efc96de36af9274269bbcbcd2c158c846c4051baaa2de5efa574e2e',
    },
    pooky_order_allow: {
      type: GraphQLString,
      description:
        'eyJ0b2hydV9vayI6IHRydWUsImVuYWJszwiQOiB0cnVlLCJhbGxfcmVsZWFzZXMiOnRydWUsInNwbGF5X2VudiI6InByb2QiLCAibW91c2Vfc2NvcmUiOjEwMCwiYnlwYXNzIjp0cnVlfQ',
    },
    pooky_performance: {
      type: GraphQLString,
      description:
        '90ff67084a669a673d32424c716f6f6b98a59dd83d5116e8187df230550341b892fff72ab92932237c175603d6f4fdc4',
    },
    pooky_recaptcha: {
      type: GraphQLString,
      description:
        'e97aea62ce991cbb72af50a9d79110d6fe4b7eac7e44abbb87bebcb5095b88c1edd028289cebf2c1fb1e69d684b8595f',
    },
    pooky_recaptcha_coherence: {
      type: GraphQLString,
      description:
        '0a48537c18a172c964265b8e0487a8e1d1f09151920859249c2f1d2a2c05fa1b57fd5c2a5766ad2545c43847ce4cc3d5',
    },
    pooky_settings: {
      type: GraphQLString,
      description:
        '6bca6fffcbd6aa398905fb9dc2a3ca1f8c803de2eee4f45fb41a4ffc70061fa1f5d3575bf720aabc2be8efb74d850bec',
    },
    pooky_telemetry: {
      type: GraphQLString,
      description:
        '67db023465119f3486c7aae6378e1b6eed727986fa248edbb36322217cc997baa78579a0239e472d3e1f343e2f79b318',
    },
    pooky_use_cookie: {
      type: GraphQLBoolean,
      description: 'true',
    },
    updated_pooky_coherence: {
      type: GraphQLString,
      description: 'bafd60d036cf80654d46b78341625b11ba67fe510fbbba40d71c00ed6a8f59cb',
    },
  }),
});
