import { GraphQLObjectType, GraphQLNonNull, GraphQLInputObjectType } from 'graphql';

import GraphQLJSON from 'graphql-type-json';

export const Cookies = new GraphQLObjectType({
  name: 'Cookies',
  description: 'Cookies generated by pooky',
  fields: () => ({
    values: {
      type: GraphQLNonNull(GraphQLJSON),
      description: 'JSON stringified Object of cookies',
    },
  }),
});

export const CookiesInputType = new GraphQLInputObjectType({
  name: 'CookiesInput',
  description: 'Input data to create/edit a Cookies Object',
  fields: () => ({
    values: {
      type: GraphQLNonNull(GraphQLJSON),
      description: 'JSON stringified Object of cookies',
    },
  }),
});
